ci updated to improve runtime

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,7 +24,7 @@ jobs:
 
   build-ubuntu:
     needs: [build_stencils]
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
 
     strategy:
       matrix:
@@ -53,7 +53,10 @@ jobs:
         gcc -DENABLE_BASIC_LOGGING -O3 -Wall -Wextra -Wconversion -Wsign-conversion -Wshadow -Wstrict-overflow -Werror -g src/coparun/runmem.c src/coparun/coparun.c src/coparun/mem_man.c -o bin/coparun
 
     - name: Install ARM binutils
-      run: sudo apt-get update && sudo apt-get install -y binutils-aarch64-linux-gnu
+      run: |
+        which aarch64-linux-gnu-objdump || echo "Not found: aarch64-linux-gnu-objdump"
+        sudo apt-get install --no-install-recommends -y binutils-aarch64-linux-gnu
+      
 
     - name: Generate debug asm files
       if: strategy.job-index == 0
